### ISSUE TITLE
login for rstudio server

### ISSUE THREAD

**Issue by thorek1** [znmeb/edgyR#1]
Hi,

excellent work setting up the image. I was excited to test this little thing and started up your image, last hurdle: login for rstudio server

From the code I take the username is either root or edgyr and the password is $EDGYR_PASSWORD but that didn't get me far.

Many thanks,

Thore

**Comment by znmeb** [comment]
The user name is `edgyr`. You set the password in the environment variable `EDGYR_PASSWORD` before running the image. The password must be at least 12 characters.

Once it comes up, browse to port 8787 on localhost inside the Jetson or to the Jetson's IP address from another machine on the LAN.

**Comment by thorek1** [comment]
works. many thanks

**Comment by thorek1** [comment]
works. many thanks
