### ISSUE TITLE
edgy user has no access to GPU

### ISSUE THREAD

**Issue by thorek1** [znmeb/edgyR#33]
if you follow the instructions as in the guide and try to run a model with TensorFlow he will use the cpu because he does not find the gpu.

this can be fixed by adding:
`usermod -a -G video $USER`

see: [here](https://forums.developer.nvidia.com/t/nvidia-docker-seems-unable-to-use-gpu-as-non-root-user/80276/6)

**Comment by znmeb** [comment]
Hmmm ... It was loading the library ... I figured it was working. Easy fix - thanks!

**Comment by znmeb** [comment]
Fix is in https://github.com/znmeb/edgyR/tree/add-miniforge-arrow
